//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("show")]
[assembly: System.Reflection.AssemblyDescription("Saves its stdin to a temporary file and opens it in the default text editor.")]
[assembly: System.Reflection.AssemblyProduct("ShowOutput")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2014-2015 Kody Brown (@kodybrown). Released under the MIT License.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("1CCFDF33-439F-4E75-B393-EC33801B694A")]
[assembly: System.Reflection.AssemblyVersion("0.1.0.51120")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0.51120")]


